modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/drtheodor/hex-spell-wheel"
license = "MIT"

[[mods]]
modId = "spellwheel"
version = "${version}"
displayName = "Hex Spell Wheel"
authors = "DrTheo_"
description = '''
An addon for Hex Casting (1.20.1) that allows you to open a wheel menu to select a spell book page!
'''
logoFile = "assets/spellwheel/icon.png"

[[dependencies.spellwheel]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.spellwheel]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.spellwheel]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.spellwheel]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "CLIENT"
